### ISSUE TITLE
compile failed - version of d3 installed is incompatible with carbon-charts

### ISSUE THREAD

**Issue by tay1orjones** [davidicus/create-iot-react-app#20]
Spin up a new app via npx and the automatically installed version of d3 is "d3": "^6.2.0", causes this error

```
Failed to compile.

./node_modules/@carbon/charts/components/axes/grid-brush.js
Attempted import error: 'event' is not exported from 'd3-selection'.
```

This version of d3 is incompatible with carbon-charts.

https://github.com/carbon-design-system/carbon-charts/issues/775

It needs to be the same version range they define in their peer deps

https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/package.json#L58

```
"d3": ">=5.0.0 <=5.14.2"
```

**Comment by davidicus** [comment]
fixed in v1.2.5
