### ISSUE TITLE
Error when starting the development server

### ISSUE THREAD

**Issue by jdorseywx** [davidicus/create-iot-react-app#24]
I get the following error when running `yarn start`:
```
Failed to compile.

./src/index.js
Module not found: Can't resolve './serviceWorker' in 'C:\src\carbon\iot3\src'
```
If I comment out the following line in index.js, everything seems to work properly:

`import * as serviceWorker from './serviceWorker';`

Running in Windows 10 with Node v12.18.1 (also tried in Linux with Node v14)

**Comment by davidicus** [comment]
Hi @jdorseywx. Thanks for reporting this. I think CRA app has dropped out of box support for service workers and I need to update my template.

**Comment by davidicus** [comment]
@jdorseywx i have [fixed](https://github.com/davidicus/create-iot-react-app/commit/b06e60f77a26e7808842cbb275f743430140ccce) and tested in a test app. This issue should be resolved. Please let me know if the problem persist for you.
